# Generated by Django 4.0.4 on 2022-07-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
